FROM openjdk:11.0

ADD target/app1-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/market_data > application.properties'
RUN sh -c 'echo spring.datasource.username=root    >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]
